# The age public key can be fetched as `age-keygen -y <KEYFILE>
keys:
  - &primary age1hz3gpqxyt6ke2qu9u5rl3egkndtpl08m75xh2njawevut3z95d2s68zujf

creation_rules:
  # Use age for everything.
  - key_groups:
      - age:
        - *primary
