# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

# <https://gist.github.com/osmano807/8b8e9b37043007c68c4cbfb69ee3e562>
# Fix for broken ath10k driver.
let
  qca9377_firmware = pkgs.callPackage ./qca9377_firmware.nix { };
in
{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bf5f3e3a-78c1-4a9d-824d-b5dbfcbc6800";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.settings.max-jobs = lib.mkDefault 4;

  hardware.firmware = with pkgs; [
    qca9377_firmware
  ];
}
